data loaded!
lr: 0.005
Traceback (most recent call last):
  File "pixel.py", line 178, in <module>
    train(model, dataloader, config )
  File "pixel.py", line 150, in train
    for batch in dataloader:
  File "/home/gmh72/.conda/envs/TensoIR3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/gmh72/.conda/envs/TensoIR3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/gmh72/.conda/envs/TensoIR3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gmh72/.conda/envs/TensoIR3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "pixel.py", line 83, in __getitem__
    return self.reflectance_GT[idx], self.mask[idx]
IndexError: index 100 is out of bounds for dimension 0 with size 100
